### ISSUE TITLE
Rats can't extract input items from rat crafting tables.

### ISSUE THREAD

**Issue by SlimF** [AlexModGuy/Rats#100]
I don't know if it's intended or not, but because they can't extract input items, recipes that require a bucket of water for example are impossible to automate.

If rats could extract input items it'd be possible to make one rat put a bucket of water in the crafting table and another one to extract the empty bucket so it can be filled again.

**Comment by mrossi80** [comment]
Similiar to https://github.com/Alex-the-666/Rats/issues/100#issue-507955820

**Comment by GizmoTheMoonPig** [comment]
Fixed in 5e5583927d7cc0727b0c8dbb162f274c0380c77e
