### ISSUE TITLE
EntityLookHelper.setLookPositionWithEntity() crash

### ISSUE THREAD

**Issue by SirAron111** [AlexModGuy/Rats#112]
https://paste.dimdev.org/cuqenareme.mccrash

Rats Mod: rats-3.1.0-1.12.2
MC: 1.12.2
Forge: 14.23.5.2847 

I am really not sure what caused this. But it somehow happened and all the mobs around where rats.

**Comment by GizmoTheMoonPig** [comment]
Should be fixed in 5e5583927d7cc0727b0c8dbb162f274c0380c77e, I hope
