### ISSUE TITLE
Buckets get deleted in crafting

### ISSUE THREAD

**Issue by bbbower** [AlexModGuy/Rats#123]
Using seablock: rustic waters and specifically the creosote oil buckets to craft the treated wood, the buckets get deleted instead of expelled at the end of the recipe, the wood planks get made correctly however.  
Suggestions : Buckets get expelled after craft requiring a bucketed liquid or an enhanced version of the table that can have liquids inserted? Mouse chemist might be good with liquids buckets and bottles ? :)

**Comment by mrossi80** [comment]
I had to use the tank+funnel+chest and create several empty iron buckets. Would be nice, for example to have the recipe product expelled at the bottom side of the table and all the craft subproducts (i.e. empty bucket) expelled on the bottom side of the rat  crafting table.

Also using the "bucket" upgrade for the rats didn't work, an enhanced crafting table would be nice.

**Comment by GizmoTheMoonPig** [comment]
Fixed in 5e5583927d7cc0727b0c8dbb162f274c0380c77e
