### ISSUE TITLE
Harvest Rat: Platter Upgrade not working

### ISSUE THREAD

**Issue by MBfromOK** [AlexModGuy/Rats#139]
Minecraft 1.12.2
ModPack: Rustic Waters

Have a pair of rats gardening for me.  
Rat #1 is the planter.
Rat #2 is the harvester.

Rat #2 has the platter upgrade, breaks mature crops,  but only gets first dropped item, misses extras, and then never goes back to collect drops from plants it harvested.

Additionally, sometime it gets hung up and you have to remove the platter upgrade for it to resume harvesting

**Comment by MobiuSRIT** [comment]
Modpack: All the Mods 6 on 1.16.1

Same issue.  I constantly have to re-equip the planter upgrade.

**Comment by GizmoTheMoonPig** [comment]
Fixed in 5e5583927d7cc0727b0c8dbb162f274c0380c77e
