### ISSUE TITLE
suggestion: rats prefer full inventories

### ISSUE THREAD

**Issue by kreezxil** [AlexModGuy/Rats#14]
have rats configurable to prefer a full inventory. Have them if they can't find food in chests, just steal stuff from a full inventory because in their little rat brains they're hoping that makes room for food to show up.

**Comment by GizmoTheMoonPig** [comment]
decided against this as checking nearby container sizes and contents can be expensive to do. The stealing from chests goal is already decently taxing and I had to reduce how often it fires because of this
