### ISSUE TITLE
Rats: Torch glitch

### ISSUE THREAD

**Issue by MBfromOK** [AlexModGuy/Rats#141]
Minecraft 1.12.2
ModPack: Rustic Waters

I understand that modpacks have the ability to modify your pack settings and that you can't necessarily support mod-pack issues, but I don't seem to see any way to white/blacklist items in the config files.

In my case my Planting & Harvesting rats think that Aquamarine torches are harvest-able food (but they can't break them, so they just stand in them dancing) , is there a harvest white/blacklist?

I have dealt with it for now by replacing the torches with Glowstone, but ouch!

**Comment by GizmoTheMoonPig** [comment]
rats will now use the minecraft:crops tag to determine what crops to break, so this will no longer be an issue. Keep in mind this is only for the soon-to-release 1.19 version, since none of the other versions are no longer supported
