### ISSUE TITLE
Ratinator has bad aim

### ISSUE THREAD

**Issue by Lance5057** [AlexModGuy/Rats#145]
I gave a rat the ratinator upgrade and so far it's managed to shoot me more than any mob we've encountered. They should probably avoid shooting if the player is between them and the target.

**Comment by GizmoTheMoonPig** [comment]
rat projectiles will no longer hurt their owners or any mobs allied with their owner. It also seems like their aim was improved at some point, theyre a really good shot now! Keeping one on your head as a mini turret is actually a ton of fun
