### ISSUE TITLE
Rat milking bull (Animania)

### ISSUE THREAD

**Issue by Krutoy242** [AlexModGuy/Rats#147]
Milkmaid rat able to milk Animania bulls.
https://imgur.com/31ozWWX

Expects only cows can provide milk.

**Comment by riskable** [comment]
Are you kidding me?  This is a feature!  I'm impressed by both the rat's gentle dexterity and the bull's ability to output his, "milk" with such regularity!

**Comment by Archilyte** [comment]
this planet's denizens have serious issues...

**Comment by GizmoTheMoonPig** [comment]
as animania hasnt left 1.12, im gonna close issues regarding it as done. 1.12 is no longer supported
