### ISSUE TITLE
[Suggestion] Animania integration

### ISSUE THREAD

**Issue by Krutoy242** [AlexModGuy/Rats#148]
1. Right now rat with Milkmaid upgrade gather **vanilla milk** from any cows (and bulls, lol). Suggesting rat milking respective breed milk (Friesian milk, Jersey milk, ect), with original restriction - Animania cows originally can be milked only when _"Ready for Milking"_ status appear.
2. Milkmaids now can't milk **Sheeps and Goats**. Suggesting to add this ability with respective milk type
3. Animania's **cheese** way harder to make (special cows, milking restrictions, several days of cheese processing). Suggest it can be converted in more Rat's cheeses or rats can be tamed with Animania's cheese faster.

**Comment by GizmoTheMoonPig** [comment]
as animania hasnt left 1.12, im gonna close issues regarding it as done. 1.12 is no longer supported
