### ISSUE TITLE
Loading Crash (1.0.1), conflict with Animalium's Rats

### ISSUE THREAD

**Issue by CaiganMythFang** [AlexModGuy/Rats#15]
Added this to my WIP modpack, but crashes when loading up.

Short part of the error is as follows : 

> java.lang.RuntimeException: Duplicate stat id: "TranslatableComponent{key='stat.entityKill', args=[TranslatableComponent{key='entity.rat.name', args=[], siblings=[], style=Style{hasParent=true, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null}}], siblings=[], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null}}" and "TranslatableComponent{key='stat.entityKill', args=[TranslatableComponent{key='entity.rat.name', args=[], siblings=[], style=Style{hasParent=true, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null}}], siblings=[], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null}}" at id stat.killEntity.rat
>     at net.minecraft.stats.StatBase.registerStat(SourceFile:41)
>     at net.minecraftforge.fml.common.registry.EntityEntryBuilder.registerStatistics(EntityEntryBuilder.java:285)
>     at net.minecraftforge.fml.common.registry.EntityEntryBuilder.access$100(EntityEntryBuilder.java:57)
>     at net.minecraftforge.fml.common.registry.EntityEntryBuilder$BuiltEntityEntry.addedToRegistry(EntityEntryBuilder.java:335)

[Full crash report here. ](https://paste.dimdev.org/hizozeyojo.mccrash) . Should include full modlist in it as well.

I did a quick test with the only other mod I have that contains a rat creature, [Animalium](https://minecraft.curseforge.com/projects/animalium?gameCategorySlug=mc-mods&projectID=263442), and disabling [Animalium ](https://minecraft.curseforge.com/projects/animalium?gameCategorySlug=mc-mods&projectID=263442)fixes the crash.

**Comment by Alex-the-666** [comment]
hmmm. you should bring this up to the animalium dev. i understand the issue, that rats isnt registering the rat entity to rats.rat, but if i did this it would kill all player's tamed rats. seeing that the rats in animalium are exclusively hostile monsters, it would be a better fix on their side.

**Comment by vadis365** [comment]
Yeah, both Alex and myself are aware of this, but tbh if I change it then it'll also mess up a few things for people in other packs, also my hostile mobs do steal items from player's hands which would delete the item if the entity is removed - not ideal. I have changed the registry names in 1.14 and 1.15 as those versions are less well used atm, but I'm afraid the best option is to remove animalium in 1.12.2 if you want to use the rats mod.

**Comment by NinetyKnight99** [comment]
> Yeah, both Alex and myself are aware of this, but tbh if I change it then it'll also mess up a few things for people in other packs, also my hostile mobs do steal items from player's hands which would delete the item if the entity is removed - not ideal. I have changed the registry names in 1.14 and 1.15 as those versions are less well used atm, but I'm afraid the best option is to remove animalium in 1.12.2 if you want to use the rats mod.


Is there any way I can make a modification that makes both mods compatible for my personal modpack?
