### ISSUE TITLE
Game crash: ClassCastException

### ISSUE THREAD

**Issue by RisingInIris2017** [AlexModGuy/Rats#154]
#### Rats version:
rats-3.2.4

#### Forge version:
forge-1.12.2-14.23.5.2838

#### Singleplayer or Multiplayer:
Multiplayer, using [Catserver](https://github.com/Luohuayu/CatServer).

#### Installed mods:
There is a list: https://paste.ubuntu.com/p/vZvmRzg92k/

## Link to full crash log
https://paste.ubuntu.com/p/yYbkWxjrGg/

**Comment by Alex-the-666** [comment]
mod compat issue. ill have to research this further

**Comment by GizmoTheMoonPig** [comment]
closing as both links have expired and I have yet to find any class casting issues. Please open a new issue if this is still a problem on modern versions of the mod
