### ISSUE TITLE
Lumberjack rat issues

### ISSUE THREAD

**Issue by Jace3458** [AlexModGuy/Rats#176]
Mostly happens right after it deposits wood it chopped. Also rat radius staff not working with lumberjack, moves outside radius to chop wood. Rat also will designate one tree to chop, if I try to move him away from it, he'll move straight back to the tree.

**Comment by GizmoTheMoonPig** [comment]
Fixed in 5e5583927d7cc0727b0c8dbb162f274c0380c77e
