### ISSUE TITLE
Rats suffocate in space despite damage protector upgrade

### ISSUE THREAD

**Issue by CosmicGlowsticks** [AlexModGuy/Rats#185]
I'm not entirely sure if it's a compatibility issue, I'm not sure how to figure that out, if that's the problem, my bad!! 
I have the damage protector upgrade on my rats, but I noticed they still take damage in space without oxygen. (I use galacticraft) Again, I'm not sure if it's a compatibility thing or not. 
I kinda wanna run around with a bunch of cyborg rats on Mars, because that sounds fun-

**Comment by GizmoTheMoonPig** [comment]
this sounds like a compat issue. I dont know what damage source they use when applying suffocation damage but its probably not a vanilla one. With damage types being moved to tags and stuff in 1.19.4 I hope this wont be an issue, but if it still is I can easily account for it nowadays
