### ISSUE TITLE
Dimension is unloading and loading until server crash

### ISSUE THREAD

**Issue by Boolyman** [AlexModGuy/Rats#188]
I have some people reporting an issue on my tracker, if you could take a look at it, thanks!

https://www.curseforge.com/minecraft/modpacks/seablock-rustic-waters/issues/212

**Comment by GizmoTheMoonPig** [comment]
all issues regarding ratlantis are being closed as the dimension has been completely rewritten from the ground up and shouldnt have these issues anymore in 1.19 and beyond.

As for the rat disappearing through the portal, thats a completely separate issue (#374) that I need to look into. Ideally, rats shouldnt dismount when going through a portal at all, but we'll see how fixable this is
