### ISSUE TITLE
[Suggestion] Add in "mouse" wheel that generates energy and can have other functions

### ISSUE THREAD

**Issue by DWX12** [AlexModGuy/Rats#19]
Thinking along the lines of the Horse Power mod where players use horses or other mobs to power various machines such as grinders, compactors, and choppers. An energy generator will probably be in the works in the future.

Thinking that this mod could have wheels for the rats to run in and the wheels could be hooked up to generators and other machines for various uses such as those in Horse Power. Of course since a rat is small and would only generate a small amount of power, multiple rats would be needed to be of any significance.

**Comment by GizmoTheMoonPig** [comment]
closing since this was added in the 1.16 version
