### ISSUE TITLE
Suggestion: Make rats greedier when collecting items off the ground

### ISSUE THREAD

**Issue by wrincewind** [AlexModGuy/Rats#198]
currently, a rat with the 'platter' upgrade will wander to the nearest item, pick it up, and wander back to its storage chest, even when there's lots of items scattered about. (e.g. fallen logs from a treefarm). I'd suggest that with this upgrade, they should grab the first item, scan the area for any more items of this type, and grab those first.  Only when they've got a full stack, or when there's no more items to collect, should they return to their storage chest. This would make the platter upgrade much more useful for item collection.

**Comment by Pultex** [comment]
The problem I have is their Zone keeps moving with them so the get too far and don't return to the chest.
The search for things past walls and will jump off ledges to their death as the search field seem to see items FAR past the their Zone

**Comment by wrincewind** [comment]
You can use the Rat Radius Staff (one bit of plague-rat skin and a stick) to bind their area of effect to a block, rather than to the rat. This helps keep them from looking too far

**Comment by GizmoTheMoonPig** [comment]
I definitely agree the platter doesnt function as it should. In 1.19, rats will collect up to a stack of similar items around them before trying to deposit into chests if they have the platter upgrade. This was definitely something that really bugged me
