### ISSUE TITLE
[Feature request] Agricraft, ic2exp and ic2classic crops compat

### ISSUE THREAD

**Issue by Froggy800** [AlexModGuy/Rats#21]
As it is right now, having a field of crops keeps the plants safe from wild rats; It would make sense for them to attack plants that are planted with crops.

**Comment by Tenchu98** [comment]
yes please

**Comment by GizmoTheMoonPig** [comment]
rats will go after any crops properly tagged under minecraft:crops in 1.19 when it releases. If mods dont tag their blocks properly that will be on them
