### ISSUE TITLE
Unable to consistently click rats into cage

### ISSUE THREAD

**Issue by IamStig** [AlexModGuy/Rats#211]
Playing MC Eternal. Made 4 cages, multi-blocked them 2x2. About 1 in 10 times I can right click a rat into the cage...I have not managed to get 2 in at once. Every fail places the rat on or beside the cage.
Eternal V1.3.4
Rats V3.2.6
MC V1.12.2
Also tried the Rat Sack ..... got 4 in sack and not able to be any in the cage.
I also removed the only mod I added to the pack....Carry On, made no difference

**Comment by GizmoTheMoonPig** [comment]
unable to reproduce this in ANY version, including MC eternal itself. Not sure why youre having issues
