### ISSUE TITLE
[Bug] Plague sometimes reappears shortly after curing it with no mobs nearby

### ISSUE THREAD

**Issue by SandwichHorror** [AlexModGuy/Rats#220]
Issue reported by a player:

**To Reproduce**
1. Spawn any plague-inducing mob.
2. Cure it with any item, while avoiding mob attacks.
3. Wait a minute or so.
4. Do it repeatedly until plague reappears with no reason.

**Expected behavior**
Plague is reinflicted only on specific mob attacks.

-------
The player said they were only interacting with chests, not animals nor hostile mobs.

**Comment by GizmoTheMoonPig** [comment]
Fixed in 5e5583927d7cc0727b0c8dbb162f274c0380c77
