### ISSUE TITLE
Bug Portal to Ratlantis in Multiplayer

### ISSUE THREAD

**Issue by Askropios** [AlexModGuy/Rats#228]
Hi, I'm currently hosting an Enigmatica 4 and noticed that the entire server crashes every time someone is trying to enter Ratlantis. I manually updated Rats to the newest version, but the problem persists.

**Comment by Alex-the-666** [comment]
crashlog please

**Comment by Deeno3107** [comment]
hi me and my friends have the same issue on a minecraft 1.14.4 server with 92 mods including rats
here is the crash report:
[crash-2020-04-16_00.36.49-server.txt](https://github.com/Alex-the-666/Rats/files/4484334/crash-2020-04-16_00.36.49-server.txt)

**Comment by phit** [comment]
welp new issue in 4.1.1
https://gist.github.com/phit/874d6edde21d23423d48bedc8e12c93f

**Comment by phit** [comment]
looks like you also need to register the dimensiontype in the `FMLCommonSetupEvent` for whatever reason..

**Comment by Askropios** [comment]
Hey, the fix didnt change anything for me.

**Comment by Askropios** [comment]
[Neues Textdokument.txt](https://github.com/Alex-the-666/Rats/files/4499093/Neues.Textdokument.txt)

Hey, the fix didnt change anything for me.

**Comment by excinere** [comment]
Temporary fix for this is to open the server's world in single player, generate the rat dimension, copy it back to the server, and then use "/execute in rats:ratlantis run tp @p 0 64 0" to get in. Use "/execute in minecraft:overworld run tp @p 0 64 0" to get out.

**Comment by Curlz242** [comment]
@excinere hi and thx. Can you please explain how to copy the rat dimension to server?

**Comment by KodeShinju** [comment]
Also having this error.
Minecraft Version: 1.14.4
Mod Version: 4.1.1

**Comment by GizmoTheMoonPig** [comment]
all issues regarding ratlantis are being closed as the dimension has been completely rewritten from the ground up and shouldnt have these issues anymore in 1.19 and beyond
