### ISSUE TITLE
[1.14.4](4.1.1) Crash from ticking entity, null vehicle

### ISSUE THREAD

**Issue by CvoidWyvern** [AlexModGuy/Rats#262]
Afk (but not paused) in a creative superflat test world just generated and the game crashed spontaneously
https://hastebin.com/zebugakogo.pl

**Comment by GizmoTheMoonPig** [comment]
closing because the log is expired, but ive fixed a couple crashes regarding mounts in dev so this may no longer be an issue whatever it is
