### ISSUE TITLE
[1.14.4] Ticking entity crash when farmer tries to plant Botania flower.

### ISSUE THREAD

**Issue by kelmes1** [AlexModGuy/Rats#264]
Crash happens when a farmer rat opens a container and tries to plant a botania flower.
Crash log:
[crash-2020-04-30_19.32.39-server.txt](https://github.com/Alex-the-666/Rats/files/4560099/crash-2020-04-30_19.32.39-server.txt)

**Comment by GizmoTheMoonPig** [comment]
Fixed in 5e5583927d7cc0727b0c8dbb162f274c0380c77
