### ISSUE TITLE
Rats despawn

### ISSUE THREAD

**Issue by felippegd** [AlexModGuy/Rats#288]
I'm using Rats-3.2.11-1.12.2 and everything was going fine, but suddenly, all my tamed rats despawned, new rats don't spawn and if i spawn a Rat with a spawn egg and leave the game, when i enter again, they disappear.

Why is this happening?

**Comment by felippegd** [comment]
i tryied to disable custommobspawner, but even with a clean game, they despawn. And don't have any option to change this.

**Comment by felippegd** [comment]
I discovered that the problem is in the version. The 3.2.10 works fine.

**Comment by BenjaminLeSire** [comment]
Known bug, see #287 .

**Comment by felippegd** [comment]
And what i need to do to fix it? I readed the link that you sent me, but i don't understand anything.

**Comment by BenjaminLeSire** [comment]
Wait for the dev to get a chance to look at the fix, and hopefully merge it. Or if you're in a hurry, you can compile it yourself. And if you don't know how to do that, I put a ready-to-use version of the mod on discord. Come say hi!

**Comment by maximogta** [comment]
try https://www.curseforge.com/minecraft/mc-mods/deuf-duplicate-entity-uuid-fix, it could fix your problem I will try it myself, because could happen to me anytime soon playing with astral sorcery and rats

**Comment by GizmoTheMoonPig** [comment]
should no longer be an issue
