### ISSUE TITLE
Rats get confused

### ISSUE THREAD

**Issue by BenjaminLeSire** [AlexModGuy/Rats#289]
Steps to reproduce:

- tame a rat
- give it Planter or Lumberjack upgrade
- remove and put upgrade back

Rat will execute both normal Harvest task and Planter/Lumberjack task.
Bug is present on 3.2.10 and 3.2.11.

**Comment by GizmoTheMoonPig** [comment]
Fixed in 5e5583927d7cc0727b0c8dbb162f274c0380c77e
