### ISSUE TITLE
Mod sounds have no distance muffling to them [1.15.2]

### ISSUE THREAD

**Issue by DarkyAlan** [AlexModGuy/Rats#305]
Version 5.3.1

As the title says, I could be 5-15 blocks away from a pied piper, a trash bin or a rat dropping nuggets and all sounds behave as if I were right next to the source.

**Comment by jschmidt1224** [comment]
From: [MC-146721](https://bugs.mojang.com/browse/MC-146721)
It seems if a sound should fade with distance, it needs to be mono as of 1.14.

I did a quick test replacing the piper and flute .oggs with mixed versions and piper sounds started to fade with distance

**Comment by GizmoTheMoonPig** [comment]
all sounds will be switched to mono in the upcoming 1.19 version, so this will no longer be a problem
