### ISSUE TITLE
Feature Request: Dimension blacklist

### ISSUE THREAD

**Issue by riskable** [AlexModGuy/Rats#307]
Yes, I know we have `"Rats Spawn In Overworld Only" = true` (thank you for that) but let me explain why I **need** the ability to blacklist _some_ dimensions while letting rats spawn in others:  The Moon.

You see, there's _cheese_ on the moon (thanks to the Space-BossTools mod dev for adding the cheese feature I specifically requested!).  Super duper saturating cheese!  Seeing rats everywhere on the moon just makes so much sense.  Rats belong there!  Especially my carefully-selected astronaut and cosmonaut rats (it's not an easy training program!).

Then you go to Mars and there's rats everywhere there too which just seems _wrong_.  Rats don't belong on Mars!  Neptune and Pluto, maybe (blue cheese).  But definitely not Mars!  Nobody wants orange-dyed imitation cheese-like products!

So I am requesting something like, `"Extinct rats dimensions" = ["boss_tools:mars"]` feature.

Your mod is fantastic BTW.  Thank you!

**Comment by GizmoTheMoonPig** [comment]
rat spawning will be controlled via a biome modifier in 1.19. What this means is you can add biomes to the new `rat_spawn_biomes` tag and rats will spawn in that biome. This should allow you to do whatever you want when it comes to configuring spawns
