### ISSUE TITLE
[1.15.2] Rats breaking crops upon harvest even if config set to false

### ISSUE THREAD

**Issue by Geethebluesky** [AlexModGuy/Rats#308]
With Rats rats-5.3.1-1.15.2, I have **"Rats Break Crops on Harvest" = false** in my config.

The single rat I've tamed at the moment, without upgrades or anything, still breaks pumpkin stems  and berry bushes completely instead of just harvesting the pumpkin itself and grabbing the berries, leaving bushes.

Forge: 31.1.88

**Comment by GizmoTheMoonPig** [comment]
fixed as shown above this message
