### ISSUE TITLE
Game consistently crashing after 2-3 hours

### ISSUE THREAD

**Issue by Cocomere** [AlexModGuy/Rats#309]
I recently updated the modpack I use, Enigmatica 4, to the newest release. Everything was fine for a few days, and then I started messing around with Rats. Once I started doing relatively light automation (4 fisherman rats, 3 gem cutters, 3 chefs, about four extras) things started going haywire. After 2-3 hours, the game fully crashes and makes my laptop act really weird in the process. I'm consistently having issues with Discord and Skype (yes I use both at once) both being nonresponsive after a crash.

I've talked to some of the people on the modpack author's Discord, and the suggestion I was given was to make a new instance and port my world over (which didn't help) and to wait for bug fixes.

[latest.log](https://github.com/Alex-the-666/Rats/files/4733203/latest.log)

Here's the log of my last session. I'd like to be able to use this mod, but it's literally screwing with my actual computer. :/

**Comment by GizmoTheMoonPig** [comment]
I wasnt able to get any crashes to happen on the 1.19 port even though I had the game up for hours so I assume this is no longer an issue. If you can still get it to happen on 1.19 please let me know
