### ISSUE TITLE
[1.12.2] trying to use rats mod in a modpack weird mod interaction

### ISSUE THREAD

**Issue by J0kerchan** [AlexModGuy/Rats#312]
after a rat spawns in world the world freezes no fps lag or server side lag everything in world just stops moving after like 10mins everything goes back to normal and the rats despawn or they stay in world game doesnt crash or give any errors ive noticed an error in the console wich created a crash log but there is no signs of an issue in game the rats even work correctly after spawned in 
[crash-2020-06-07_18.19.57-server.txt](https://github.com/Alex-the-666/Rats/files/4743159/crash-2020-06-07_18.19.57-server.txt)

**Comment by vengefulgod** [comment]
not sure if this is the right place to post this if not please forgive me I was playing the mod pack called dimension zero and got a crash log 
[crash-2020-06-21_10.13.34-server.txt](https://github.com/Alex-the-666/Rats/files/4809775/crash-2020-06-21_10.13.34-server.txt) saying rat the problem if you can look into this I will really be glad about it if it fixable

**Comment by GizmoTheMoonPig** [comment]
this was an issue with a UUID being saved/loaded to the rat. This should no longer happen, not sure if it was fixed in 1.12 but is definitely fixed in 1.16
