### ISSUE TITLE
Flying Dutchrat can drown, and goes out of its own aggro range

### ISSUE THREAD

**Issue by Carro1001** [AlexModGuy/Rats#315]
If the flying dutchrat boss is underwater for long enough, it can take drowning damage, which probably isn't intended as it's a ghost that can phase thru any blocks.

it can also get too far from the player during the fight, and start targetting other entities instead

**Comment by GizmoTheMoonPig** [comment]
Fixed in 5e5583927d7cc0727b0c8dbb162f274c0380c77
