### ISSUE TITLE
Ratlantis portal generates in spawn coordinates instead of Overworld portal's

### ISSUE THREAD

**Issue by Carro1001** [AlexModGuy/Rats#318]
I've recently noticed, that's the reason the portal usually never generates where it's supposed to, it takes the Overworld's first spawnpoint and builds the portal there, and the game randomly chooses where you'll end up in ratlantis, the overworld portal's coords, or the ratlantis portal's coords, at least that's what seems to happen.

**Comment by Lelong-vincent** [comment]
Any news about this bug ?

I started a server with some friends on the MC Eternal modpack, bough a token from the shop to create a portal to Ratlantis and  got the same bug, I spawned high in the sky (certainly at the same coordinates I was in the overworld, the portal is on top of a mountain). There was no portal at my spawn point in Ratlantis. I can't check right now if there is a portal in 0,0 cuz I'm waiting for the server owner to teleport me (I'm really far away), but I suppose that's where the portal is.

As this was on a modpack I tried in creative mode on a fresh profile with only the Rats mod (MC version 1.12.2). This time I spawned near the portal at 0,0 coordinate, but I was not on the platform and fell off. As the portal was high (120+ block high) I would have died certainly if I wasn't in creative. Also when I took back the portal to go to the overworld, I spawned in the overworld at the same coordinate of the portal in Ratlantis (0, 120+, 0), so again I was mid air and would have suffer a big falling damage.

I would say the Ratlantis portail should behave like every other dimension portal both in vanilla and other mods : when you enter the dimension your spawn coordinate correspond at your overworld coordinates, and a portal is created where you spawn. And of course you should not be teleported back at 0,0 in the overworld when leaving Ratlantis by the same portal.

**Comment by GizmoTheMoonPig** [comment]
Fixed in 5e5583927d7cc0727b0c8dbb162f274c0380c77
