### ISSUE TITLE
[1.15.2] Server crashes after player loads

### ISSUE THREAD

**Issue by mr-poyo** [AlexModGuy/Rats#324]
Forge: 31.2.20
Version: rats-5.3.1-1.15.2.jar

Hello,

I have a server with a custom modpack and we noticed that when a specific player joins the server hangs until a crash. He does have the rats mod in his base and it wasn't crashing previously. But lately he cannot really play anymore without stalling the server. Here is the crash log. Thank you! 

Update: this crash is actually inconsistent. Doesn't happen all the time. 

Crash report: https://pastebin.com/aTdd3XnN

**Comment by GizmoTheMoonPig** [comment]
Should be fixed in 5e5583927d7cc0727b0c8dbb162f274c0380c77e
