### ISSUE TITLE
[1.12.2] [BUG] Keeping entity rats:rat that already exists... x800

### ISSUE THREAD

**Issue by bchilcott** [AlexModGuy/Rats#326]
A rat on my server was left on "hunt mobs" mode for a while, and kept into the corner of a room and being "squished too much", and then immediately respawning and repeating the process. 

I think some part of him remains in the corner, since standing there in survival causes players to also get "squished too much". Standing in the area in creative and doing `/kill @e[type=rats:rat,r=2]` prints "Killed GARGANAX" (rat's name) in the console a few hundred times.

Repeating the kill command prints "Entity [UUID of rat owner] cannot be found" the same number of times. When the server reloads and the kill command is repeated, both messages are printed again when you attempt to kill the invisible rats.

I'm aware there's probably more info I need to give (and this description is trash) but it's hard to know what info is relevant. I'll provide more if needed.

Debug log from when the rat infested chunk was loaded here, but can upload the full log if necessary:
https://pastebin.com/re47rpFi

Mod Version: 3.2.12
MC Version: 1.12.2
Modpack: MC Eternal 1.3.6

**Comment by Alex-the-666** [comment]
What does "squished too much" mean?

**Comment by Scythern** [comment]
There are too many mobs in one space. I believe it's vanilla.

https://minecraft.fandom.com/wiki/Death

**Comment by GizmoTheMoonPig** [comment]
Should be fixed in 5e5583927d7cc0727b0c8dbb162f274c0380c77
