### ISSUE TITLE
rats disappear

### ISSUE THREAD

**Issue by dkholodkov** [AlexModGuy/Rats#328]
Hello!  faced with such a problem that the tamed rats disappear with tags did, still help pliz

**Comment by Alex-the-666** [comment]
1.12.2 or 1.15.2?

**Comment by dkholodkov** [comment]
1.12.2

**Comment by GizmoTheMoonPig** [comment]
Should be fixed in 5e5583927d7cc0727b0c8dbb162f274c0380c77
