### ISSUE TITLE
Feral Ratlanteans are invisible and cause insane console spam

### ISSUE THREAD

**Issue by voidswrath** [AlexModGuy/Rats#330]
Version: rats-3.2.13-1.12.2 the issue was also present on 3.2.5 I tried upgrading to fix
Mod List: https://gyazo.com/fa38f01feb4ad25da02b1d98abb569bd

I was struggling to find them and now I know why hahah

https://gyazo.com/090d169b78e0954fd718b0ff2a50d153

**Comment by GizmoTheMoonPig** [comment]
im not able to reproduce this. Im 99% sure this is some wacky mod conflict, but not sure what the problem is here. Definitely not a Rats problem tbh
