### ISSUE TITLE
[1.15.2] Bugs with Ratlantis Portal and World Gen

### ISSUE THREAD

**Issue by guacamonkey** [AlexModGuy/Rats#333]
When using the ratlantis portal to enter ratlantis, it seems to randomly pick between teleporting to the portal on the ratlantis side, and another nearby location, where it then drops you out of the air. When leaving ratlantis through the portal, it either spawns you at a specific location near the portal (in my case by a nether portal, though this may be unrelated) or at your bed. 
Finally, sometimes, when entering the portal to leave ratlantis, it will spawn me back next to the ratlantis portal in ratlantis. Sometimes, when this happens, the world gen of ratlantis will corrupt and chunks seem to be locally scrambled (some staying the same, some being replaced or shifted). Additionally, when traveling ratlantis, it will crash the server, even moreso when in the corrupted state.
Based on other bugs, this may be related to an interaction with another mod that is in our pack: nomadic tents, YUNG's Better caves, or Quark.

**Comment by GizmoTheMoonPig** [comment]
all issues regarding ratlantis are being closed as the dimension has been completely rewritten from the ground up and shouldnt have these issues anymore in 1.19 and beyond
