### ISSUE TITLE
[1.12.2] Game Crashing due to plague rats spawned by Black Death

### ISSUE THREAD

**Issue by Starfox8641** [AlexModGuy/Rats#336]
I spawned the Black Death by drinking Destabilized Redstone with a straw (Summons lightning and sets player on fire)
The game crashed consistently until a friend TP'ed me out of the area **Before the chunk loaded.**
This was client side and no other members on the server experienced crashes and were nowhere near the Crash Area

Client Log: [Crash.txt](https://github.com/Alex-the-666/Rats/files/4874265/Crash.txt)

Mod List: https://www.curseforge.com/minecraft/modpacks/minecraft-eternal/files/2981794

I'll happily answer any questions to the best of my ability

**Comment by GizmoTheMoonPig** [comment]
unable to reproduce, I assume this was fixed at some point
