### ISSUE TITLE
Rats mod breaks vanilla mob AI for picking up items [1.16.1]

### ISSUE THREAD

**Issue by flashgnash** [AlexModGuy/Rats#338]
Zombies, skeletons and most importantly villagers for breeding purposes are unable to pickup items while the rats mod is installed. Villagers will look at the items they would normally pick up, but be unable to actually pick them up.

**Comment by GizmoTheMoonPig** [comment]
I dont know how this even happened in the first place tbh, but it should be fixed in 5e5583927d7cc0727b0c8dbb162f274c0380c77e
