### ISSUE TITLE
Rats can create a hole in Stone Bricks

### ISSUE THREAD

**Issue by jschmidt1224** [AlexModGuy/Rats#347]
While playing on 1.16.1 with Rats 6.0.1 I found a Rat Hole made from stone bricks

I found it when a Plague Doctor had spawned nearby with 2 pet rats, I believe it was one of the pets that did it, but I can't be sure.

![Rathole](https://user-images.githubusercontent.com/4556054/87254667-ed7fa680-c438-11ea-801c-83bfbbf8d5a9.png)

**Comment by GizmoTheMoonPig** [comment]
fixed as seen in the message above this
