### ISSUE TITLE
Cannot create ratglove flowers with bonemeal in Ratlantis

### ISSUE THREAD

**Issue by shanekremer** [AlexModGuy/Rats#348]
According to the Wiki:
https://rats-mod.fandom.com/wiki/Ratlantis

I should be able to grow ratglove flowers by putting bonemeal on grass in Ratlantis.

This is not working for me and I am just growing regular grass.

I am on Minecraft 1.15.2
Forge 31.2.29
Rats 5.3.2

**Comment by s2h** [comment]
Same problem

Minecraft 1.16.4
Forge 35.1.13
Rats 7.0.1-1.16.3
Ratlantis 1.0.0-1.16.3

Modpack Allthemods 6-1.3.7

**Comment by GizmoTheMoonPig** [comment]
Fixed in 5e5583927d7cc0727b0c8dbb162f274c0380c77e
