### ISSUE TITLE
1.16 Rats and Biomes O Plenty Issue.

### ISSUE THREAD

**Issue by whatthedrunk** [AlexModGuy/Rats#349]
1. Create a new world on 1.16.1 Forge version 32.0.63 with only Rats and Citadel. 
2. Save and close the game.
3. Add Biomes O Plenty and load the game.
4. Game gets stuck on "reading world data..." and you cant load it.
5. Creating a new world works fine.

**Comment by GizmoTheMoonPig** [comment]
BOP issue states its no longer an issue apparently, so i'll assume its fixed
