### ISSUE TITLE
Horrible Lag and Server Console Spam

### ISSUE THREAD

**Issue by Rithenar** [AlexModGuy/Rats#350]
I am experiencing some horrible lag while playing in Ratlantis. No lag in Overworld, Nether, or End (only other dimensions visited so far). I am rubber banding 5-6 times before I get to where I stop when flying or running. Also blocks reappear after breaking them. My FPS is dropping to 5-6 constantly (normally 50-60).

I am playing on a private server hosted by BisectHosting and they have ran all the tests and find nothing wrong with the server or network connection.

I have lowered render distance to 4 and Graphics to Fast, no particles and no clouds (normally run render to 12 and Fancy Graphics with all options on). Using no shaders, resource packs or Optifine.

Server console spam constantly giving "Player moved to quickly" message and server overloaded. As soon as I go to overworld everything goes back to normal. 
![image](https://user-images.githubusercontent.com/9939332/87368474-62d79e00-c543-11ea-86be-f8959de343d7.png)

**Comment by Rithenar** [comment]
If it helps determine the source of the issues, BisectHosting ran a region fixer for me since the chunks were really corrupted and found large corruption in the dimension
![image](https://user-images.githubusercontent.com/9939332/87439781-c9e26a80-c5b6-11ea-9c49-f01ba9b89ee3.png)

They recommended to delete the DIM and allow it to rebuild, which I did.  Here is the server log. The problems are still there. 
https://gist.github.com/Rithenar/ddf5e9e0c83fde0c75e20e111023c1e0

**Comment by GizmoTheMoonPig** [comment]
all issues regarding ratlantis are being closed as the dimension has been completely rewritten from the ground up and shouldnt have these issues anymore in 1.19 and beyond
