### ISSUE TITLE
Portal to ratlantis not working.

### ISSUE THREAD

**Issue by papuSpartan** [AlexModGuy/Rats#353]
For whatever reason the portal to ratlantis, in multiplayer, isn't doing anything. I checked the logs and there are no errors whatsoever.

Java version: 8
Rats Version: latest stable 1.16
Forge version: 32.0.63

**Comment by jdawg3636** [comment]
I'm having the same issue - works in singleplayer but not on a dedicated server.

MC: 1.16
Forge: 32.0.75
Citadel: citadel-1.2.0.jar
Rats: rats-6.0.4-1.16.1.jar

**Comment by krispydreams** [comment]
yeah same multiplayer portals to ratlantis doesnt work

**Comment by Sebaitax** [comment]
donts works 11/08/2020

**Comment by eehunter** [comment]
Same issue here, enigmatica 6 with rats, IaF, Silent's Gems, and Silent Gear added. Rats 6.0.6. Using "/execute in" shows that "rats:ratlantis" appears to be missing from the registry.

**Comment by GizmoTheMoonPig** [comment]
this was a big issue with custom dimensions in 1.16. To fix it simply run the /reload command twice and restart the server. Should fix it right up. This should no longer be an issue in 1.19 once the mod finishes updating to it
