### ISSUE TITLE
[1.16.1] Synesthesia bleaches hotbar and is dark

### ISSUE THREAD

**Issue by ZeWolfTah** [AlexModGuy/Rats#358]
Forge version: forge-1.16.1-32.0.69
Rats version: rats-6.0.4-1.16.1
SSP/SMP: SMP

Description: The Synesthesia buff is much darker than it was in older updates making it hard to see when underground, and it also bleaches out the hotbar making it harder to tell what item is selected.

Steps to replicate: Eat "Confit Byaldi", observe hotbar and observe visibility while underground.

Mods:
AppleSkin-mc1.16.1-forge-1.0.14
citadel-1.2.0
cloth-config-forge-4.0.1
Controlling-7.0.0.2
CTM-MC1.16.1-1.1.0.1
Ding-1.16.1-1.1.0
FastLeafDecay-v23
ironchest-1.16.1-11.0.1
ironshulkerboxes-1.16.1-5.0.1
jei-1.16.1-7.0.0.6
light-overlay-5.4.1
Mekanism-1.16.1-10.0.2.425
MekanismAdditions-1.16.1-10.0.2.425
MekanismGenerators-1.16.1-10.0.2.425
MekanismTools-1.16.1-10.0.2.425
MouseTweaks-2.13-mc1.16.1
rats-6.0.4-1.16.1
refinedstorage-1.9.2
StorageDrawers-1.16.1-8.0.0
valhelsia_structures-16.0.1
Waystones_1.16.1-7.0.2

![2020-07-18_00 31 43](https://user-images.githubusercontent.com/27912891/87847623-95103500-c88e-11ea-88be-429c2e35fc43.png)

Edit: The darkness effect is easier to see if you try it in the nether. It's SUPER dark.

**Comment by aikainnet** [comment]
you cannot see at all in the end, atm6 at the end

**Comment by GizmoTheMoonPig** [comment]
Fixed in 5e5583927d7cc0727b0c8dbb162f274c0380c77e
