### ISSUE TITLE
[1.16.1] Sounds are centered on player and not the entity making them

### ISSUE THREAD

**Issue by ZeWolfTah** [AlexModGuy/Rats#359]
Forge version: forge-1.16.1-32.0.69
Rats version: rats-6.0.4-1.16.1
SSP/SMP: SMP

Description: Sounds coming from mobs such as rats and the pied piper are centered on the player, making it hard to locate where the mob causing the sound is, and also making it constantly louder since volume is based on distance from the source.

Steps to replicate: Turn sounds on. Stay different distances from the pied piper and listen to the audio.

Mods:
AppleSkin-mc1.16.1-forge-1.0.14
citadel-1.2.0
cloth-config-forge-4.0.1
Controlling-7.0.0.2
CTM-MC1.16.1-1.1.0.1
Ding-1.16.1-1.1.0
FastLeafDecay-v23
ironchest-1.16.1-11.0.1
ironshulkerboxes-1.16.1-5.0.1
jei-1.16.1-7.0.0.6
light-overlay-5.4.1
Mekanism-1.16.1-10.0.2.425
MekanismAdditions-1.16.1-10.0.2.425
MekanismGenerators-1.16.1-10.0.2.425
MekanismTools-1.16.1-10.0.2.425
MouseTweaks-2.13-mc1.16.1
rats-6.0.4-1.16.1
refinedstorage-1.9.2
StorageDrawers-1.16.1-8.0.0
valhelsia_structures-16.0.1
Waystones_1.16.1-7.0.2

**Comment by GizmoTheMoonPig** [comment]
see #305 for an explanation as to why this was happening
