### ISSUE TITLE
[1.12.2] Shift clicking a stack of Milk Buckets into a Curdling Station deletes all but the first

### ISSUE THREAD

**Issue by aaronhowser1** [AlexModGuy/Rats#361]
![image](https://user-images.githubusercontent.com/15698722/87865222-4cad5180-c938-11ea-97aa-f91937b569f7.png)
![image](https://user-images.githubusercontent.com/15698722/87865224-520a9c00-c938-11ea-8df0-2c17c83a0b9b.png)
Using `rats-3.2.13-1.12.2`

**Comment by GizmoTheMoonPig** [comment]
I dont know what mod allows for bucket stacking like that, but regardless, the input slot will only accept a stack size of 1 in 1.19 and above
