### ISSUE TITLE
[1.16] Rat Entity Duping

### ISSUE THREAD

**Issue by NielsPilgaard** [AlexModGuy/Rats#362]
Copied from issue https://github.com/NillerMedDild/Enigmatica6/issues/15

`rats-6.0.4-1.16.1`

**Issue**
Server reboots are causing some Rats to get duplicated (example, this white rat with bucket, I have only ever created one of them
**Edit: No reboot required, relogging works too.**
![2020-07-19_11 40 48](https://user-images.githubusercontent.com/6739653/87882676-93da2780-c9b6-11ea-92f9-5b0fc55687e8.png)

same with these rats. however the Remy rat seen here in the top left has never duplicated.
![2020-07-19_11 40 57](https://user-images.githubusercontent.com/6739653/87882502-27aaf400-c9b5-11ea-8509-ad1d1aea38df.png)

I presume only the original seems to get duplicated (which is why there are 3 and not 4) after 3 server reboots
Edit: No reboot required, relogging works too.

**Comment by GizmoTheMoonPig** [comment]
gonna assume this is no longer a problem since the issue it was reposted from is resolved? Ive personally never experienced this so I cant say for sure. Gonna close this regardless, if you happen to encounter this in a later version of the mod let me know and i'll further troubleshoot it
