### ISSUE TITLE
Dimension Generation issue, grave stone removed due to gen issue, and chunk serializer error on load in, causing server to crash

### ISSUE THREAD

**Issue by Teslachu** [AlexModGuy/Rats#365]
So basically the dimension does not generate properly

It also seems to get regularly corrupted and then regenerates the chunks.
Due to this, a player completely lost their gravestone and everything they had.
The dimension does not generate very well. Many areas look like it was just cut off and is incomplete for a chunk.
Every time you go into the dimension, you basically fall to your death.
Then after you get in there, it tends to cause the server to time out and crash. After you crash, you are back where you left off (from quite some time ago. It keeps resetting how far back you were). 
Trying to leave the dimension causes the server to crash.

(Sorry I can't provide the crash logs. I got upset and deleted the crash logs, along with the dimension. Teleported back to the overworld, after it regenerated the dimension and stopped the server. Because of the pack, it is part of and the issues going on, there is no way to progress and with the fact that everything was lost, I am done.)

**Comment by GizmoTheMoonPig** [comment]
all issues regarding ratlantis are being closed as the dimension has been completely rewritten from the ground up and shouldnt have these issues anymore in 1.19 and beyond
