### ISSUE TITLE
[1.15.2][ATM5] Ratlantis Crash

### ISSUE THREAD

**Issue by tonitetelol** [AlexModGuy/Rats#367]
When playing on an All The Mods5 Server, whenever I enter to Ratlantis the server crashes, spamming in console: "Unable to get Dimension name"

The crash log: [https://pastebin.com/1ETBDe46](url)

**Comment by tonitetelol** [comment]
Oh, also mention that I edited de dimension ID in config because it conflicts with the mining dimension.

**Comment by Thunder-Nova** [comment]
I am using the official ATM 5 server and can still confirmed it crashes I managed to see Ratlantis just before it crashes.

At one time a mod called [Advanced Mining Dimension](https://www.curseforge.com/minecraft/mc-mods/advanced-mining-dimension) did interfere with the teleportation crash aftermath, and ended up teleporting into that dimension.

@Alex-the-666 that info might help in finding the code

**Comment by GizmoTheMoonPig** [comment]
since dimensions no longer use numerical IDs in 1.16 and beyond, this will never be an issue anymore
