### ISSUE TITLE
Rats duplicate (1.12.2)

### ISSUE THREAD

**Issue by TheLoganizer42** [AlexModGuy/Rats#370]
I dont know if this is just an MC Eternal bug, or maybe a thing on my end, but after a couple of minutes in a world, a duplicate "ghost" of every tame rat appears. It can be interacted with, has all the same tags, but if you try to move it it teleports back very quickly. These ghost rats are also invulnerable as far as I know and will disappear after relogging, only to come back a few minutes later.

Update: sometimes they duplicate again, and can be stored in a rat sack, allowing them to be permanent.

**Comment by GizmoTheMoonPig** [comment]
this most likely has to do with the issue with UUIDs in 1.12, but that should be long fixed by now. Maybe not in 1.12, but it is for sure in later versions
