### ISSUE TITLE
[1.15.2] Plague Doctors overrunning my area

### ISSUE THREAD

**Issue by JakeMoe** [AlexModGuy/Rats#371]
I've got a mostly underground base, so I spend most of my time either mining or building.  As I've got some resources growing, I've been afk a bit as well, and the world has been running for probably 2 days straight.  I noticed there seemed to be a fair amount of villager noises and potion drinking sounds coming from the surface, so I went to go have a look.  Found 19 plague doctors in a 2 x 2 chunk area.  Seems excessive?  Is this intended?

Minecraft: 1.15.2
Forge: 31.2.30
Rats: 5.3.2-1.15.2

**Comment by GizmoTheMoonPig** [comment]
wandering plague doctors were set to never despawn due to a typo in the code. This will no longer be an issue once the 1.19 version is released.

**Comment by Shibva** [comment]
THEIR ALIVE!
