### ISSUE TITLE
[1.16] Rats get confused/stop working

### ISSUE THREAD

**Issue by thenewdreamer** [AlexModGuy/Rats#373]
very frequently rats will just stop in their tracks and not do whatever they're assigned to do until they fall a little bit. You can see a few rats paused in this video, and even see the skull delivering rat stopping directly.
I usually see it happening inside of non-blocks, like flowers, redstone dust or levers.
(on Vazkii's patreon server, if you want to check it out personally)
https://www.youtube.com/watch?v=4dWbb-2fKtk

**Comment by GizmoTheMoonPig** [comment]
fixed, as seen in the commit linked above
