### ISSUE TITLE
Rat vanishes when taken across dimensions

### ISSUE THREAD

**Issue by smilodon79** [AlexModGuy/Rats#374]
Mod Version:  3.2.13

Issue:  Take a rat (on your person) across a portal and it doesn't make it through.  It's not present in the overworld when I get back either.

Steps:

1.  Make a rat (in my case, it was a nonbeliever, flight, damage protection, asbesto rat, voodoo)
2.  Shift+Right click it to get it onto your head
3.  Go through the portal to ratlantis
The rat is missing when you get there.  It's missing even when you get back.  Shift+Clicking, using the flute, using the sack with net, none of them report that the rat's around anymore.  Given the upgrades I used on this rat, this was a very expensive bug :).

**Comment by GizmoTheMoonPig** [comment]
Fixed in 5e5583927d7cc0727b0c8dbb162f274c0380c77e
