### ISSUE TITLE
Lily pad duplication

### ISSUE THREAD

**Issue by direct91** [AlexModGuy/Rats#391]
When a rat has the Replanter upgrade, when harvesting a Lily Pad the result will be a lily pad left, and one in its hands.  The rat will then drop off the lily pad in its storage, and then attempt to harvest the lily pad again, resulting in a loop.  Found in All The Mods 5, version 2.13, Minecraft version 1.15.2, which uses rats version 5.3.2.  Also happens with a Lily Pad of Fertility.

Note of preferred functionality:  If I give a rat the replanter upgrade, it is because I want it working on a farm, and I may have lily pads to cover water, or the lilypad of fertility to speed up growth, either of which I would not want removed.

**Comment by ben-mkiv** [comment]
not a fix for the issue, but as workaround to fix your farm, you can use trapdoors to cover your water (which can be placed within the water blocks)

**Comment by GizmoTheMoonPig** [comment]
fixed by #715
