### ISSUE TITLE
No data fixer registered for Entity 1.16.1

### ISSUE THREAD

**Issue by carlosgspsp** [AlexModGuy/Rats#397]
17.08 00:44:39 [Server] modloading-worker-51/ERROR No data fixer registered for rat
17.08 00:44:39 [Server] modloading-worker-51/ERROR No data fixer registered for rat_spawner
17.08 00:44:39 [Server] modloading-worker-51/ERROR No data fixer registered for pied_piper
17.08 00:44:39 [Server] modloading-worker-51/ERROR No data fixer registered for ratlantean_spirit
17.08 00:44:39 [Server] modloading-worker-51/ERROR No data fixer registered for ratlantean_spirit_flame
17.08 00:44:39 [Server] modloading-worker-51/ERROR No data fixer registered for ratlantean_automaton
17.08 00:44:39 [Server] modloading-worker-51/ERROR No data fixer registered for ratlantean_automaton_beam
17.08 00:44:39 [Server] modloading-worker-51/ERROR No data fixer registered for feral_ratlantean
17.08 00:44:39 [Server] modloading-worker-51/ERROR No data fixer registered for neo_ratlantean
17.08 00:44:39 [Server] modloading-worker-51/ERROR No data fixer registered for laser_beam
17.08 00:44:39 [Server] modloading-worker-51/ERROR No data fixer registered for laser_portal
17.08 00:44:39 [Server] modloading-worker-51/ERROR No data fixer registered for thrown_block
17.08 00:44:39 [Server] modloading-worker-51/ERROR No data fixer registered for vial_of_sentience
17.08 00:44:39 [Server] modloading-worker-51/ERROR No data fixer registered for pirat_boat
17.08 00:44:39 [Server] modloading-worker-51/ERROR No data fixer registered for pirat
17.08 00:44:39 [Server] modloading-worker-51/ERROR No data fixer registered for cheese_cannonball
17.08 00:44:39 [Server] modloading-worker-51/ERROR No data fixer registered for plague_doctor
17.08 00:44:39 [Server] modloading-worker-51/ERROR No data fixer registered for purifying_liquid
17.08 00:44:39 [Server] modloading-worker-51/ERROR No data fixer registered for black_death
17.08 00:44:39 [Server] modloading-worker-51/ERROR No data fixer registered for plague_cloud
17.08 00:44:39 [Server] modloading-worker-51/ERROR No data fixer registered for plague_beast
17.08 00:44:39 [Server] modloading-worker-51/ERROR No data fixer registered for plague_shot
17.08 00:44:39 [Server] modloading-worker-51/ERROR No data fixer registered for rat_capture_net
17.08 00:44:39 [Server] modloading-worker-51/ERROR No data fixer registered for rat_dragon_fire
17.08 00:44:39 [Server] modloading-worker-51/ERROR No data fixer registered for rat_arrow
17.08 00:44:39 [Server] modloading-worker-51/ERROR No data fixer registered for ghost_pirat
17.08 00:44:39 [Server] modloading-worker-51/ERROR No data fixer registered for dutchrat
17.08 00:44:39 [Server] modloading-worker-51/ERROR No data fixer registered for dutchrat_sword

**Comment by KuebelHund** [comment]
I got the same issue, but everything runs fine, some people say, that you can ignore that error.

**Comment by GizmoTheMoonPig** [comment]
this is not a dangerous warning message, and nothing bad will happen because of it. It wont show up on future versions due to Minecraft code changes, but you can safely ignore it
