### ISSUE TITLE
Intense pathfinding lag

### ISSUE THREAD

**Issue by williewillus** [AlexModGuy/Rats#398]
I took this profiler dump from Vazkii's Patron server this morning, when there have been no players online for several hours.

https://spark.lucko.me/#A3QyI2Canl

Rat pathfinding to follow owners ends up accounting for over half of all tick time (keep expanding the largest subsection until you get to it).

Either something's buggy with the follow logic or it's happening too often. What non-player entities can own rats and can we disable them?

**Comment by williewillus** [comment]
![image](https://user-images.githubusercontent.com/2015032/90531633-e89aca80-e13b-11ea-8312-7df6cceed028.png)

**Comment by AlexModGuy** [comment]
it looks like them rats are trying to follow a player that isnt online so the path navigate is going haywire.

**Comment by GizmoTheMoonPig** [comment]
looks like this was already fixed a while ago, sure hope thats still the case lol
