### ISSUE TITLE
Mining and pathfinding issues

### ISSUE THREAD

**Issue by phossyjaw** [AlexModGuy/Rats#399]
When sending my rats off to mine (with the advanced miner upgrade, and blocks selected), they will begin to dig directly beside the chest. This quickly becomes an issue when the rat begins to make stairs back up to the chest, as it often will destroy it's own path, then get stuck and quit mining entirely. This even happens with the ender upgrade combined, despite the rat's ability to teleport.
The rat will also eventually end up breaking the chest as well, especially if it is a double-wide chest.
I also think there should be an additional option added to the Cheese Staff that can designate where to mine (and perhaps how deep, far, duration, etc.).
Edit: This is occurring in the 1.16.1 version, I am unaware of the behavior in other versions.

**Comment by GizmoTheMoonPig** [comment]
Fixed in 5e5583927d7cc0727b0c8dbb162f274c0380c77e
