### ISSUE TITLE
Plague Potion Icon overlaps other potions

### ISSUE THREAD

**Issue by WenXin20** [AlexModGuy/Rats#53]
Forge v14.23.2838
Rats v2.0.0
 
As seen in the image below, the Plague Potion Icon overlaps the other potions.
![2019-08-01_21 18 48](https://user-images.githubusercontent.com/12000593/62340171-3185cf80-b4a4-11e9-9350-8d131fd95eed.png)

**Comment by GizmoTheMoonPig** [comment]
seems to no longer be an issue in 1.19
