### ISSUE TITLE
[suggestion] villagers fight back

### ISSUE THREAD

**Issue by Morinor** [AlexModGuy/Rats#54]
As of now, villages are completely defenseless against rats stealing loot from chests and most importantly, destroying crops.
Id suggest that villagers scare rats away in a wide radius, and/or rats cant spawn in villages.

With the addition of wild village cats in 1.14+ (once the mod gets there), id suggest that cats not only scare rats off, but also actively hunt them down, should they get near a village.

**Comment by BrisingrAerowing** [comment]
Ocelots hunt rats in 1.12.2, and the Not Enough Cats mod makes them spawn in villages, like in 1.14.x. I believe tamed cats will hunt rats as well.

**Comment by GizmoTheMoonPig** [comment]
cats, ocelots, and foxes will attack wild rats, as well iron golems (this one is configurable). Villages should be decently safe from rats in newer versions because of this
