### ISSUE TITLE
Rat Pathfinding needs Improvement

### ISSUE THREAD

**Issue by Mr-Lycan** [AlexModGuy/Rats#60]
A few of my rats have had pathing issues, preferring to huddle in a corner rather than do their jobs. The AI can be jumpstarted again by forcing an item into their hands but only for a short time.

**Comment by gabrieldip002** [comment]
I've been also having similar issues. I have also noticed that rats is taking quite a hefty amount of my server's resources, as noted by TickProfiler.

13.10 19:27:22 [Server] EntityProfiler/INFO [TickProfiler]:
13.10 19:27:22 [Server] INFO TPS: 19.96201
13.10 19:27:22 [Server] INFO Single Entity | Time/Tick | %
13.10 19:27:22 [Server] INFO EntityFireDragon -373,19,56:0 | 0.794 | 2.292
13.10 19:27:22 [Server] INFO entity.EntityRat -258,31,412:0 | 0.792 | 2.287
13.10 19:27:22 [Server] INFO entity.EntityRat 30,15,421:0 | 0.501 | 1.444
13.10 19:27:22 [Server] INFO entity.EntityRat -282,39,444:0 | 0.455 | 1.312
13.10 19:27:22 [Server] INFO citizen.EntityCitizen -256,69,300:0 | 0.448 | 1.290
13.10 19:27:22 [Server] INFO Chunk | Time/Tick | %
13.10 19:27:22 [Server] Startup 0: -17, 25 | 1.322 | 3.810
13.10 19:27:22 [Server] Startup 0: -13, -3 | 0.873 | 2.515
13.10 19:27:22 [Server] Startup 0: -24, 3 | 0.795 | 2.293
13.10 19:27:22 [Server] Startup 0: -12, -2 | 0.765 | 2.205
13.10 19:27:22 [Server] Startup 0: -13, 21 | 0.596 | 1.719
13.10 19:27:22 [Server] INFO All Entities of Type | Time/Tick | %
13.10 19:27:22 [Server] INFO entity.EntityRat | 11.183 | 32.237
13.10 19:27:22 [Server] INFO prehistoric.EntityNautilus | 3.659 | 10.548
13.10 19:27:22 [Server] INFO citizen.EntityCitizen | 3.240 | 9.340
13.10 19:27:22 [Server] INFO EntityWroughtnaut | 1.311 | 3.778
13.10 19:27:22 [Server] INFO monster.EntityZombie | 1.214 | 3.500
13.10 19:27:22 [Server] INFO Average Entity of Type | Time/tick | Calls
13.10 19:27:22 [Server] INFO EntityFireDragon | 0.801 | 603
13.10 19:27:22 [Server] INFO TileEntityElectricFurnace | 0.250 | 602
13.10 19:27:22 [Server] INFO CowHereford$EntityCowHereford | 0.167 | 570
13.10 19:27:22 [Server] INFO citizen.EntityCitizen | 0.164 | 11991
13.10 19:27:22 [Server] INFO entity.EntityRat | 0.154 | **43740**

**Comment by bbbower** [comment]
Same issues, seems stairs pose more of a problem than stairs, and if I use pipes they all run to the x/z of the pipes ignoring the y and get stuck jumping around or if they manage to get into a pipe thats where they now live.

**Comment by GizmoTheMoonPig** [comment]
Hello! During the 1.19 port I took it upon myself to rewrite how rats pathfind and perform tasks, so this should no longer be an issue. If you still find problems in the port please let me know and I'll address them. Thanks!
