### ISSUE TITLE
WHAT!!!!?

### ISSUE THREAD

**Issue by pantsguyapp** [AlexModGuy/Rats#777]
Why is there tags for a new version of fhis mod? Is it the long waited 1.18 version?

**Comment by GizmoTheMoonPig** [comment]
im working on the 1.19 version as we speak. Ive almost got a beta ready to go.

Please dont put things like this in the issue tracker, ive been working really hard to clean it up

**Comment by pantsguyapp** [comment]
1 19 versions? Not 1.18?

**Comment by GizmoTheMoonPig** [comment]
No. 1.18 is a horrible version to do dimension modding in. I would have to rewrite quite a bit of the mod itself again plus I would have to start from scratch on ratlantis. I don't have time for that, I'm already very short on free time

**Comment by pantsguyapp** [comment]
Oh... thank you for your respond, Im sad now cause I want to use the mod along side VH 1.18.
