### ISSUE TITLE
My rats have eaten atleast about 100 blocks worth of cheese yet none have been tamed.

### ISSUE THREAD

**Issue by Someone9219231** [AlexModGuy/Rats#796]
So i was playing my game and i tryed to tame some rats after getting ALOT of cheese cause its weird like that. and i drop it and they go through 6 STACKS OF CHEESE Please tell my atleast a way of sorts to fix it? i even opened to lan cheats on and got Creative cheese! they refused to even touch it

**Comment by GizmoTheMoonPig** [comment]
which version is this on? Do black smoke particles appear when the rat picks up a piece of cheese? If not it sounds like some other mod may be modifying/removing the thrower tag on the item. 
If you're gonna use creative cheese you'll need to right click the rat with it, not throw the cheese at it.

**Comment by GizmoTheMoonPig** [comment]
closing due to lack of additional info. If youre still having this issue open a new ticket
