### ISSUE TITLE
[Suggestion] Allow inputs to Rat Crafting Table from the sides

### ISSUE THREAD

**Issue by Hjaldar** [AlexModGuy/Rats#91]
The crafting rat placed on top of a Rat Crafting Table can sometimes be pushed off the crafting table by the rat delivering items to the crafting table, because the crafting table only accepts inputs from the top.

If the Rat Crafting Table also accepted inputs from the side this problem would be alleviated.

**Comment by GizmoTheMoonPig** [comment]
Added in 5e5583927d7cc0727b0c8dbb162f274c0380c77e
